---
- hosts: bips
  become: yes
  tasks:
    - name: Install BIPS service
      apt:
        name: bips
        state: present

- hosts: ng_siem
  become: yes
  tasks:
    - name: Install NG SIEM service
      apt:
        name: ng-siem
        state: present
    - name: Ensure NG SIEM running
      service:
        name: ng-siem
        state: started
        enabled: yes

- hosts: ng_soc
  become: yes
  tasks:
    - name: Install NG SOC service
      apt:
        name: ng-soc
        state: present
    - name: Ensure NG SOC running
      service:
        name: ng-soc
        state: started
        enabled: yes
