---
- hosts: training_platform
  become: yes
  tasks:
    - name: Install training web server
      apt:
        name: nginx
        state: present
    - name: Ensure nginx running
      service:
        name: nginx
        state: started
        enabled: yes

- hosts: trainee_workstation
  become: yes
  tasks:
    - name: Install pentest tools
      apt:
        name:
          - nmap
          - gvm
        state: present

- hosts: cyber_range
  become: yes
  tasks:
    - name: Install DVWA dependencies
      apt:
        name:
          - apache2
          - mysql-server
        state: present

- hosts: randomization_platform
  become: yes
  tasks:
    - name: Install randomization utilities
      apt:
        name: python3
        state: present

- hosts: bips
  become: yes
  tasks:
    - name: Install BIPS service
      apt:
        name: bips
        state: present

- hosts: ng_siem
  become: yes
  tasks:
    - name: Install NG SIEM service
      apt:
        name: ng-siem
        state: present
    - name: Ensure NG SIEM running
      service:
        name: ng-siem
        state: started
        enabled: yes

- hosts: cicms
  become: yes
  tasks:
    - name: Install CICMS service
      apt:
        name: cicms
        state: present

- hosts: ng_soc
  become: yes
  tasks:
    - name: Install NG SOC service
      apt:
        name: ng-soc
        state: present
    - name: Ensure NG SOC running
      service:
        name: ng-soc
        state: started
        enabled: yes
