- name: Download CTEMS package
  ansible.builtin.get_url:
    url: "{{ ngsoc_repo_url }}/ctems/ctems-agent.deb"
    dest: "/tmp/ctems-agent.deb"
    mode: "0644"
    checksum: "{{ ctems_agent_checksum }}"
  become: yes

- name: Install CTEMS
  ansible.builtin.apt:
    deb: "/tmp/ctems-agent.deb"
    state: present
  become: yes

- name: Configure CTEMS
  ansible.builtin.template:
    src: ctems.conf.j2
    dest: /etc/ctems/config.yml
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Configure CTI feed URL
  ansible.builtin.template:
    src: cti_feed.env.j2
    dest: /etc/ctems/cti_feed.env
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Deploy malware simulation scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/opt/ctems/{{ item.dest }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - src: load_malware_simulation.ps1
      dest: load_malware_simulation.ps1
    - src: "{{ playbook_dir }}/../scripts/benign_malware_simulator.ps1"
      dest: benign_malware_simulator.ps1
  become: yes

- name: Enable and start CTEMS service
  ansible.builtin.service:
    name: ctems
    state: started
    enabled: yes
  become: yes

- name: Install CTI enrichment dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-requests
      - python3-stix2
    state: present
    update_cache: yes
  become: yes

- name: Deploy CTI feed fetcher script
  ansible.builtin.copy:
    src: fetch_cti_feed.sh
    dest: /opt/ctems/fetch_cti_feed.sh
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: Install fetch-cti-feed service
  ansible.builtin.template:
    src: fetch-cti-feed.service.j2
    dest: /etc/systemd/system/fetch-cti-feed.service
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Enable and start fetch-cti-feed service
  ansible.builtin.service:
    name: fetch-cti-feed
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
