---
id: recovery
name: Service Recovery
description: Restore normal operations after eradication.
start: enable_iface
actions:
  enable_iface:
    description: Re-enable network interface
    command: "ssh {{host}} 'sudo ip link set eth0 up'"
    next: verify_services
  verify_services:
    description: Verify critical services
    command: "ssh {{host}} 'systemctl status critical.service'"
