---
- name: Install CICMS
  ansible.builtin.apt:
    name: cicms
    state: present
    update_cache: yes
  become: yes

- name: Configure CICMS
  ansible.builtin.template:
    src: cicms.conf.j2
    dest: /etc/cicms/config.yml
    owner: root
    group: root
    mode: '0644'
  become: yes


- name: Enable and start CICMS service
  ansible.builtin.service:
    name: cicms
    state: started
    enabled: yes
  become: yes

