---
- name: Deploy Filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /tmp/filebeat.yml

- name: Simulate Elastic Stack installation
  ansible.builtin.debug:
    msg: "Elastic Stack components installed"
