- name: Download CICMS package
  ansible.builtin.get_url:
    url: "https://packages.internal.example.com/cicms/cicms-server.deb"
    dest: "/tmp/cicms-server.deb"
    mode: "0644"
  become: yes

- name: Download MISP package
  ansible.builtin.get_url:
    url: "https://packages.internal.example.com/misp/misp-server.deb"
    dest: "/tmp/misp-server.deb"
    mode: "0644"
  become: yes

- name: Install CICMS
  ansible.builtin.apt:
    deb: "/tmp/cicms-server.deb"
    state: present
  become: yes

- name: Install MISP
  ansible.builtin.apt:
    deb: "/tmp/misp-server.deb"
    state: present
  become: yes

- name: Configure CICMS
  ansible.builtin.template:
    src: cicms.conf.j2
    dest: /etc/cicms/config.yml
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Configure MISP
  ansible.builtin.template:
    src: misp.conf.j2
    dest: /etc/misp/misp.conf
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Enable and start CICMS service
  ansible.builtin.service:
    name: cicms
    state: started
    enabled: yes
  become: yes

- name: Enable and start MISP service
  ansible.builtin.service:
    name: misp
    state: started
    enabled: yes
  become: yes
