- name: Download NG-SIEM package
  ansible.builtin.get_url:
    url: "{{ ngsoc_repo_url }}/ng-siem/ng-siem-server.deb"
    dest: "/tmp/ng-siem-server.deb"
    mode: "0644"
    checksum: "{{ ng_siem_server_checksum }}"
  become: yes

- name: Install NG-SIEM
  ansible.builtin.apt:
    deb: "/tmp/ng-siem-server.deb"
    state: present
  become: yes

- name: Configure NG-SIEM
  ansible.builtin.template:
    src: ng_siem.conf.j2
    dest: /etc/ng_siem/config.yml
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Configure Filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/ng_siem/filebeat.yml
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Ensure BIPS log directory exists
  ansible.builtin.file:
    path: /var/log/bips
    state: directory
    mode: "0755"
  become: yes

- name: Enable BIPS log input for Filebeat
  ansible.builtin.blockinfile:
    path: /etc/ng_siem/filebeat.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK BIPS"
    insertafter: '^filebeat.inputs:'
    block: |2
      - type: log
        paths:
          - /var/log/bips/alerts.json
        fields:
          log_type: bips
        json.keys_under_root: true
        json.add_error_key: true
  become: yes

- name: Restart Filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: yes
  become: yes

- name: Configure Winlogbeat
  ansible.builtin.template:
    src: winlogbeat.yml.j2
    dest: /etc/ng_siem/winlogbeat.yml
    owner: root
    group: root
    mode: "0644"
  become: yes

- name: Enable and start NG-SIEM service
  ansible.builtin.service:
    name: ng-siem
    state: started
    enabled: yes
  become: yes
